spring.application.name=attendance-control
server.port=${PORT:8080}
server.address=${ADDRESS:0.0.0.0}


app.front-url-http=${FRONT}
app.front-url-https=${FRONT_HTTPS}

spring.datasource.url=jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=${DB_DDL}
spring.jpa.open-in-view=true

spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:10}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN:2}
spring.datasource.hikari.connection-timeout=${DB_POOL_TIMEOUT_MS:30000}
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

logging.level.org.springframework=WARN
logging.level.com.elias.attendancecontrol=INFO
